name: Release version pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Prepare signing keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/signing-key.jks

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew test

      - name: Build release APK
        run: >
          ./gradlew assembleRelease
          -Pandroid.injected.signing.store.file=${{ github.workspace }}/signing-key.jks
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_KEY_NAME }}
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Build release bundle
        run: >
          ./gradlew bundleRelease
          -Pandroid.injected.signing.store.file=${{ github.workspace }}/signing-key.jks
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_KEY_NAME }}
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Cleanup signing keystore
        run: rm $GITHUB_WORKSPACE/signing-key.jks

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.aab
